const constants = {
  API_LOGIN_LOAD: "API_LOGIN_LOAD",
  API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
  API_LOGIN_FAIL: "API_LOGIN_FAIL",
  API_LOGIN_ERROR: "API_LOGIN_ERROR",

  API_RESEND_EMAIL_LOAD: "API_RESEND_EMAIL_LOAD",
  API_RESEND_EMAIL_SUCCESS: "API_RESEND_EMAIL_SUCCESS",
  API_RESEND_EMAIL_FAIL: "API_RESEND_EMAIL_FAIL",
  API_RESEND_EMAIL_ERROR: "API_RESEND_EMAIL_ERROR",

  API_REGISTER_LOAD: "API_REGISTER_LOAD",
  API_REGISTER_SUCCESS: "API_REGISTER_SUCCESS",
  API_REGISTER_FAIL: "API_REGISTER_FAIL",
  API_REGISTER_ERROR: "API_REGISTER_ERROR",

  API_FORGOT_LOAD: "API_FORGOT_LOAD",
  API_FORGOT_SUCCESS: "API_FORGOT_SUCCESS",
  API_FORGOT_FAIL: "API_FORGOT_FAIL",
  API_FORGOT_ERROR: "API_FORGOT_ERROR",

  API_UPDATE_PROFILE_LOAD: "API_UPDATE_PROFILE_LOAD",
  API_UPDATE_PROFILE_SUCCESS: "API_UPDATE_PROFILE_SUCCESS",
  API_UPDATE_PROFILE_FAIL: "API_UPDATE_PROFILE_FAIL",
  API_UPDATE_PROFILE_ERROR: "API_UPDATE_PROFILE_ERROR",

  API_NOTIFICATION_LIST_LOAD: "API_NOTIFICATION_LIST_LOAD",
  API_NOTIFICATION_LIST_SUCCESS: "API_NOTIFICATION_LIST_SUCCESS",
  API_NOTIFICATION_LIST_FAIL: "API_NOTIFICATION_LIST_FAIL",
  API_NOTIFICATION_LIST_ERROR: "API_NOTIFICATION_LIST_ERROR",

  API_MAP_DATA_LOAD: "API_MAP_DATA_LOAD",
  API_MAP_DATA_SUCCESS: "API_MAP_DATA_SUCCESS",
  API_MAP_DATA_FAIL: "API_MAP_DATA_FAIL",
  API_MAP_DATA_ERROR: "API_MAP_DATA_ERROR",

  API_REPORT_INCIDENT_LOAD: "API_REPORT_INCIDENT_LOAD",
  API_REPORT_INCIDENT_SUCCESS: "API_REPORT_INCIDENT_SUCCESS",
  API_REPORT_INCIDENT_FAIL: "API_REPORT_INCIDENT_FAIL",
  API_REPORT_INCIDENT_ERROR: "API_REPORT_INCIDENT_ERROR",

  API_GET_ALL_INCIDENT_LOAD: "API_GET_ALL_INCIDENT_LOAD",
  API_GET_ALL_INCIDENT_SUCCESS: "API_GET_ALL_INCIDENT_SUCCESS",
  API_GET_ALL_INCIDENT_FAIL: "API_GET_ALL_INCIDENT_FAIL",
  API_GET_ALL_INCIDENT_ERROR: "API_GET_ALL_INCIDENT_ERROR",

  API_GET_INCIDENT_LOAD: "API_GET_INCIDENT_LOAD",
  API_GET_INCIDENT_SUCCESS: "API_GET_INCIDENT_SUCCESS",
  API_GET_INCIDENT_FAIL: "API_GET_INCIDENT_FAIL",
  API_GET_INCIDENT_ERROR: "API_GET_INCIDENT_ERROR",

  API_GET_INCIDENT_DETAIL_LOAD: "API_GET_INCIDENT_DETAIL_LOAD",
  API_GET_INCIDENT_DETAIL_SUCCESS: "API_GET_INCIDENT_DETAIL_SUCCESS",
  API_GET_INCIDENT_DETAIL_FAIL: "API_GET_INCIDENT_DETAIL_FAIL",
  API_GET_INCIDENT_DETAIL_ERROR: "API_GET_INCIDENT_DETAIL_ERROR",

  API_CHANGE_PASSWORD_LOAD: "API_CHANGE_PASSWORD_LOAD",
  API_CHANGE_PASSWORD_SUCCESS: "API_CHANGE_PASSWORD_SUCCESS",
  API_CHANGE_PASSWORD_FAIL: "API_CHANGE_PASSWORD_FAIL",
  API_CHANGE_PASSWORD_ERROR: "API_CHANGE_PASSWORD_ERROR",

  API_SEND_SOS_LOAD: "API_SEND_SOS_LOAD",
  API_SEND_SOS_SUCCESS: "API_SEND_SOS_SUCCESS",
  API_SEND_SOS_FAIL: "API_SEND_SOS_FAIL",
  API_SEND_SOS_ERROR: "API_SEND_SOS_ERROR",

  API_GET_RELATED_INCIDENT_LOAD: "API_GET_RELATED_INCIDENT_LOAD",
  API_GET_RELATED_INCIDENT_SUCCESS: "API_GET_RELATED_INCIDENT_SUCCESS",
  API_GET_RELATED_INCIDENT_FAIL: "API_GET_RELATED_INCIDENT_FAIL",
  API_GET_RELATED_INCIDENT_ERROR: "API_GET_RELATED_INCIDENT_ERROR",

  API_GET_MISSING_OBJECT_LOAD: "API_GET_MISSING_OBJECT_LOAD",
  API_GET_MISSING_OBJECT_SUCCESS: "API_GET_MISSING_OBJECT_SUCCESS",
  API_GET_MISSING_OBJECT_FAIL: "API_GET_MISSING_OBJECT_FAIL",
  API_GET_MISSING_OBJECT_ERROR: "API_GET_MISSING_OBJECT_ERROR",

  API_PROCEDURE_READING_LOAD: "API_PROCEDURE_READING_LOAD",
  API_PROCEDURE_READING_SUCCESS: "API_PROCEDURE_READING_SUCCESS",
  API_PROCEDURE_READING_FAIL: "API_PROCEDURE_READING_FAIL",
  API_PROCEDURE_READING_ERROR: "API_PROCEDURE_READING_ERROR",

  API_ADMIN_EMAIL_LOAD: "API_ADMIN_EMAIL_LOAD",
  API_ADMIN_EMAIL_SUCCESS: "API_ADMIN_EMAIL_SUCCESS",
  API_ADMIN_EMAIL_FAIL: "API_ADMIN_EMAIL_FAIL",
  API_ADMIN_EMAIL_ERROR: "API_ADMIN_EMAIL_ERROR",

  API_LOGOUT_LOAD: "API_LOGOUT_LOAD",
  API_LOGOUT_SUCCESS: "API_LOGOUT_SUCCESS",
  API_LOGOUT_FAIL: "API_LOGOUT_FAIL",
  API_LOGOUT_ERROR: "API_LOGOUT_ERROR",

  API_SAVE_LOCATION_LOAD: "API_SAVE_LOCATION_LOAD",
  API_SAVE_LOCATION_SUCCESS: "API_SAVE_LOCATION_SUCCESS",
  API_SAVE_LOCATION_FAIL: "API_SAVE_LOCATION_FAIL",
  API_SAVE_LOCATION_ERROR: "API_SAVE_LOCATION_ERROR",

  API_EMERGENCY_CONTACTS_LOAD: "API_EMERGENCY_CONTACTS_LOAD",
  API_EMERGENCY_CONTACTS_SUCCESS: "API_EMERGENCY_CONTACTS_SUCCESS",
  API_EMERGENCY_CONTACTS_FAIL: "API_EMERGENCY_CONTACTS_FAIL",
  API_EMERGENCY_CONTACTS_ERROR: "API_EMERGENCY_CONTACTS_ERROR",

  USER_DETAILS: "USER_DETAILS",

  SETTINGS_DETAIL: "SETTINGS_DETAIL",

  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
};

module.exports = {
  constants
};
